---
exclude: ^(notes/)
repos:
  - hooks:
      - args:
          - --branch
          - master
        id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - id: prettier
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
