---
exclude: ^(notes/)
repos:
  - hooks:
      - args:
          - --branch
          - master
        id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude_types:
          - json
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: yarn run eslint
        language: node
        types:
          - javascript
          - ts
          - tsx
  - repo: local
    hooks:
      - id: ts
        name: ts
        entry: yarn tsc
        language: node
        types:
          - ts
          - tsx
  - repo: https://github.com/AleksaC/circleci-cli-py
    rev: v0.1.22924
    hooks:
      - id: circle-ci-validator
