---
# .circleci/.config.yml reference: https://circleci.com/docs/configuration-reference/
# YAML 1.2 spec: https://yaml.org/spec/1.2-old/spec.html
# Reusable config: https://circleci.com/docs/reusing-config/
# Multiline comnads: https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
version: 2.1

# Node orb: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

parameters:
  ubuntu-image-tag:
    type: string
    default: "2023.01"

# Node image: https://circleci.com/developer/images/image/cimg/base
executors:
  node-executor:
    docker:
      - image: cimg/base:<< pipeline.parameters.ubuntu-image-tag >>

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker compose build
      - run: docker compose run -v .:/app:cache web /bin/bash -c "whoami && ls -al && /home/vscode/.local/bin/pre-commit run -a" 
workflows:
  lint-and-test:
    jobs:
      - build:
          context:
            - context