---
# .circleci/.config.yml reference: https://circleci.com/docs/configuration-reference/
# YAML 1.2 spec: https://yaml.org/spec/1.2-old/spec.html
# Reusable config: https://circleci.com/docs/reusing-config/
# Multiline comnads: https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
version: 2.1

# Node orb: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

parameters:
  ubuntu-image-tag:
    type: string
    default: 2022.10.2

# Image: https://circleci.com/developer/machine/image/ubuntu-2204
executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:<< pipeline.parameters.ubuntu-image-tag >>
      docker_layer_caching: true

jobs:
  build:
    executor: ubuntu-executor
    steps:
      - checkout
      - run: docker compose build
      - run: ls -al
      - run: docker compose run web /bin/bash -c "pwd && whoami && ls -al && git status && /home/vscode/.local/bin/pre-commit run -a" 
workflows:
  lint-and-test:
    jobs:
      - build:
          context:
            - context