version: 2.1


# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

parameters:
  cache-version:
    type: integer
    default: 1
  image-tag:
    type: string
    default: 18.2.0

# See: https://circleci.com/developer/images/image/cimg/node
executors:
  node-executor:
    docker:
      - image: cimg/node:<< pipeline.parameters.image-tag >>

jobs:
  pre-commit:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - >-
              lint-cache
              -v<< pipeline.parameters.cache-version >>
              -{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Install pre-commit
          command: |
            sudo apt-get update
            sudo apt-get install --no-install-recommends -y python3-pip
      - save_cache:
          paths:
            - ~/.cache/pre-commit
          key: >-
            lint-cache
            -v<< pipeline.parameters.cache-version >>
            -{{ checksum ".pre-commit-config.yaml" }}
      - run: pre-commit --version

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  lint-and-test:
    jobs:
      - pre-commit:
          context:
            - context
