---
# .circleci/.config.yml reference: https://circleci.com/docs/configuration-reference/
# YAML 1.2 spec: https://yaml.org/spec/1.2-old/spec.html
# Reusable config: https://circleci.com/docs/reusing-config/
# Multiline comnads: https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
version: 2.1

# Node orb: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

parameters:
  ubuntu-image-tag:
    type: string
    default: 2022.10.2

# Image: https://circleci.com/developer/machine/image/ubuntu-2204
executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:<< pipeline.parameters.ubuntu-image-tag >>
      docker_layer_caching: true

jobs:
  build:
    executor: ubuntu-executor
    steps:
      - checkout
      - run: 
          name: Create workspace directory
          command: mkdir -p workspace
      - run: 
          name: Build Docker image
          command: docker compose build
      - run: 
          name: Save image
          command: docker save -o workspace/project-web.tar project-web
      - persist_to_workspace:
          root: workspace
          paths:
            - project-web.tar
  pre-commit:
    executor: ubuntu-executor
    steps:
      - checkout
      - attach_workspace:
          at: ./workspace
      - run: ls -al workspace
      - run: 
          name: Load Docker image
          command: docker load -i ./workspace/project-web.tat
      - run: docker images
      - run: 
          name: Build Docker image
          command: docker compose build
      - run: 
          name: Run pre-commit
          command: >-
            docker compose run web /bin/bash 
            -c "sudo chown -R vscode:vscode . && ~/.local/bin/pre-commit run -a"
workflows:
  lint-and-test:
    jobs:
      - build:
          context:
            - context
      - pre-commit:
          requires:
            - build